### PR TITLE
add package-lock.json to .gitignore

### PR DESCRIPTION
**Pull request by GhostOf0days**

### CODE REVIEW

**Comment by cirex-web** [comment]
uhh this might be a bit sus...

From npm:
> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.

Also, https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

**Comment by GhostOf0days** [comment]
We stopped using npm. We migrated to bun. Bun uses bun.lockb. Look at the Slack. Also, Gabriel said he kight push the use of bun in other projects.

**Comment by GhostOf0days** [comment]
Bun uses package.json and bun.lockb.

**Comment by cirex-web** [comment]
oh cool, I didn't know you migrated the API to bun as well

**Comment by GhostOf0days** [comment]
ah ok

**Pull request merged**
