### PR TITLE
fix: don't update cache with data that's missing locations

### LINKED ISSUE #152: [Feature] Data caching
### Description

I was told that any web scraping/processing failure would trigger a complete data wipe, which is probably not good.

### Designs

_No response_

### PR DESCRIPTION
**Pull request by cirex-web**
# Description
Key change:
```ts
  if (locations.length < cachedLocations.length - 1) {
    console.log(
      "Ignored location fetch since it (likely) has missing data",
      locations
    );
  } else {
    cachedLocations = locations;
    console.log("Dining API cache reloaded");
  }
```
I did a -1 on the length just in case some location legitimately disappeared between fetches

Closes #152 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by GhostOf0days** [comment]
Thank you. Looks good to me. Once that check passes, I'll merge.

**Comment by cirex-web** [comment]
I fixed that check in the other branch by re-adding the `bun build` command. should I do it here as well?

**Comment by GhostOf0days** [comment]
No. Once that PR gets merged, you can just add a "dummy commit" like adding one space of something to make sure the check runs.

**Comment by cirex-web** [comment]
??

**Comment by GhostOf0days** [comment]
Just add a space near a comment to rerun the check. Check should pass since code is good.

**Comment by cirex-web** [comment]
well it wouldn't pass until I merged it with main lol

**Review by GhostOf0days — APPROVED** [review]

**Pull request merged**
